### ISSUE TITLE
Minor issue update ntp and satellite 6.1 on rhel 7

### ISSUE THREAD

**Issue by isnuryusuf** [boogiespook/sat6_healthCheck#7]
please also include check chronyd service as ntp server at rhel 7

Error: Either :uri or :apidoc_cache_dir needs to be set
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: No such sub-command 'organization'

See: 'hammer --help'

Error: Either :uri or :apidoc_cache_dir needs to be set
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: No such sub-command 'location'

See: 'hammer --help'
- 4 Locations found
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: No such sub-command 'location'

See: 'hammer --help'
- Details for location "An" are in /tmp/sat6_check/location_An
- 0 Subnet(s) found for An
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: No such sub-command 'location'

See: 'hammer --help'
- Details for location "An" are in /tmp/sat6_check/location_An
- 0 Subnet(s) found for An
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: No such sub-command 'location'

See: 'hammer --help'
- Details for location "An" are in /tmp/sat6_check/location_An
- 0 Subnet(s) found for An
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: No such sub-command 'location'

See: 'hammer --help'
- Details for location "An" are in /tmp/sat6_check/location_An
- 0 Subnet(s) found for An

Error: Either :uri or :apidoc_cache_dir needs to be set
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: No such sub-command 'capsule'

See: 'hammer --help'
- 4 Capsule(s) found
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: No such sub-command 'capsule'

See: 'hammer --help'
- Details for capsule "An" are in /tmp/sat6_check/capsule_An
- Features: 
- Checking DNS entries for error
  [ERROR] 3    Forward DNS does not resolve 
  [ERROR] 4    Reverse DNS not resolvable for  
  [ERROR] 5    Forward and reverse DNS do not match for error /  
- Checking network connectivity between rhsatellite.kesawan.bnk and error
  ping: unknown host error
  [ERROR] 6    error is not responding to ping? 
- Subnets
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: No such sub-command 'subnet'

See: 'hammer --help'
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: Either :uri or :apidoc_cache_dir needs to be set
Error: No such sub-command 'subnet'

See: 'hammer --help'
- Details for subnet "An" are in /tmp/sat6_check/subnet_An
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: No such sub-command 'subnet'

See: 'hammer --help'
- Details for subnet "An" are in /tmp/sat6_check/subnet_An
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: No such sub-command 'subnet'

See: 'hammer --help'
- Details for subnet "An" are in /tmp/sat6_check/subnet_An
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: Either :uri or :apidoc_cache_dir needs to be set
  Error: No such sub-command 'subnet'

**Comment by my0373** [comment]
Hi, are you able to confirm this issue has been closed with merge #9

**Comment by boogiespook** [comment]
Hi Matt,

Yep - all sorted :-)

   Chris

On 01/14/2016 09:57 AM, Matt York wrote:

> Hi, are you able to confirm this issue has been closed with merge #9 
> https://github.com/boogiespook/sat6_healthCheck/pull/9
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/boogiespook/sat6_healthCheck/issues/7#issuecomment-171591760.

## 

Chris Jenkins
Senior Architect (EMEA)
e: chrisj@redhat.com
m: +44 (0)7824140194

Registered Address:
Red Hat UK Ltd,
64 Baker Street,
4th Floor,
London  W1U 7DF,
United Kingdom.

Registered in UK and Wales under Company Registration No. 3798903
Directors: Michael Cunningham (USA), Michael O'Neill(Ireland), Matt Parson
(USA), Charlie Peters (USA)
